server:
  port: 8080
spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  #rate limiter userdan kelgan so`rovlar sonini sanash uchun redis
  data:
    redis:
      port: 6379
      host: localhost

  cloud:
    gateway:
      default-filters:
        - TokenBucketRateLimiter
      discovery:
        locator:
          enable: true
      routes:

        - id: user-service
          uri: lb://user-service
          predicates:
            - name: Path
              args:
                regexp: /user-service/**
          filters:
            - name: RequestRateLimiter_redis_rate-limiter
              args:
                redis-rate-limiter.replenishRate: 500
                redis-rate-limiter.burstCapacity: 1000
                redis-rate-limiter.requestedTokens: 1

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - name: Path
              args:
                regexp: /auth-service/**


        - id: account-service
          uri: lb://account-service
          predicates:
            - name: Path
              args:
                regexp: /account-service/**

#gatewaay rate limiter actuator uchun config
management:
  health:
    refresh:
      enabled: true