server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enable: true
      routes:
        - id: user-service
          predicates:
            - name: Path
              args:
                regexp: /user-service/**
          uri: lb://user-service

        - id: user-service
          predicates:
            - name: Path
              args:
                regexp: /auth-service/**
            - name: Cookie
              args:
                name: myCookie
                regexp: myCookieValue
          uri: lb://auth-service

        - id: user-service
          predicates:
            - name: Path
              args:
                regexp: /user-service/**
          uri: lb://user-service