server:
  port: 8002
  servlet:
    context-path: /auth-service
  error:
    include-binding-errors: always
spring:
  config:
    import: database-config.yml

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
