server:
  port: 8002
  servlet:
    context-path: /auth-service
  error:
    include-binding-errors: always
spring:
  config:
    import: classpath:database-config.yml

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

#user-service metirkalarini olish uchun ishlatiladi
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  health:
    diskspace:
      enabled: true
    circuitbreakers:
      ebabled: true
    ratelimiters:
      enabled: true
  metrics:
    tags:
      application:
        ${spring.application.name}
    distribution:
      percentiles-histogram:
        http:
          server:
            requests:
              true
        resilience4j:
          cicuitbreaker:
            calls:
              true

resilience4j:
  circuitbreaker:
    config:
      default:
        registerHealthIndicator: true
    instances:
      user-service:
        register-helth-indicator: true
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-translation-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 6s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
