server:
  port: 8001
  servlet:
    context-path: /user-service
  error:
    include-binding-errors: always
spring:
  config:
    import: database-config.yml

kafka:
  producer:
    bootstrap-server: "localhost:9092"
    key-serializer: "StringSerializer.class"
    value-serializer: "StringSerializer.class"