server:
  port: 8001
  servlet:
    context-path: /user-service
  error:
    include-binding-errors: always
spring:
  config:
    import: database-config.yml

kafka:
  producer:
    bootstrap-server: "localhost:9092"
    key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
    value-serializer: "org.apache.kafka.common.serialization.StringSerializer"
    byte-value-serializer: "org.apache.kafka.common.serialization.ByteArraySerializer"
